export const cartItemsFromApi = [
    {
        productId: "NDASU!(DNnasnNUasn(dnsaMN 1",
        productName: "PC Gamer Concórdia AMD Ryzen",
        productImage: "https://picsum.photos/seed/picsum/200/300",
        unitPrice: 1000,
        limit: 10,
        quantity: 1,
        lowerLimit: 0,
    },
    {
        productId: "9asdm1w98ASAEM@Dadasda!@",
        productName: "PC Gamer Concórdia AMD Ryzen 2 ",
        productImage: "https://picsum.photos/seed/picsum/200/300",
        unitPrice: 1000,
        limit: 10,
        quantity: 1,
        lowerLimit: 0,
    },
    {
        productId: "ASOMD@(!@masdcASJ(D!ND9oMN",
        productName: "PC Gamer Concórdia AMD Ryzen 3 ",
        productImage: "https://picsum.photos/seed/picsum/200/300",
        unitPrice: 1000,
        limit: 10,
        quantity: 1,
        lowerLimit: 0,
    },
    {
        productId: "ASOMD@(!@masdcASJ(D!ND9oMN3",
        productName: "PC Gamer Concórdia AMD Ryzen 3 ",
        productImage: "https://picsum.photos/seed/picsum/200/300",
        unitPrice: 1000,
        limit: 10,
        quantity: 1,
        lowerLimit: 0,
    },
    {
        productId: "ASOMD@(!@masdcASJ(D!ND9oMNx31",
        productName: "PC Gamer Concórdia AMD Ryzen 3 ",
        productImage: "https://picsum.photos/seed/picsum/200/300",
        unitPrice: 1000,
        limit: 10,
        quantity: 1,
        lowerLimit: 0,
    },
];